spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yourcaryourway?useSSL=false&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
